apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: board
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ${IMAGE_REPOSITORY}/board
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: board
      chartPath: deploy/helm
      valuesFiles:
      - ${VALUES_LOCATION}/board.yaml