###############################
# DEFAULT 
###############################
enabled: true
developer: false
grpc: true
scheduler: false
worker: false
name: board
replicas: 1
replicas_worker: 1     # replica number of worker
    
image:
    name: pyengine/board
    version: latest
imagePullPolicy: IfNotPresent

# Overwrite database
database:
    DATABASES:
        default:
            db: board
            host: localhost
            port: 27028
            username: admin
            authentication_source: admin
            password: spaceonedbuser
            read_preference: PRIMARY
            maxPoolSize: 200

# Overwrite application config
application_grpc: {}

# Overwrite scheduler config
application_scheduler: {}

# Overwrite worker config
application_worker: {}

##########################
# local sidecar
##########################
#sidecar:


##########################
# Local volumes
##########################
volumes:
    - name: timezone
      hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
    - name: log-volume
      emptyDir: {}



#######################
# global variable
#######################
global:
    shared: {}
    backend:
        sidecar: []
#        - name: mongos
#          image: mongo:4.4.0-bionic
#          command: [ 'mongos', '--config', '/mnt/mongos.yml', '--bind_ip_all' ]
#          volumeMounts:
#            - name: mongos-conf
#              mountPath: /mnt/mongos.yml
#              subPath: mongos.yml
#              readOnly: true
#            - name: mongo-shard-key
#              mountPath: /opt/mongos/mongo-shard.pem
#              subPath: mongodb-key-file.pem
#              readOnly: true

        volumes: []
#        - name: mongo-shard-key
#          secret:
#              defaultMode: 0400
#              secretName: mongo-shard-key
#        - name: mongos-conf
#          configMap:
#              name: mongos-conf

# Service
#service:
#    grpc:
#        type: LoadBalancer
#        annotations:
#            service.beta.kubernetes.io/aws-load-balancer-type: nlb
#            external-dns.alpha.kubernetes.io/hostname: board.dev.spaceone.dev
#        ports:
#            - name: grpc
#              port: 50051
#              nodePort: 30055
#              protocol: TCP   
#


################################
# volumeMount per deployment
################################
volumeMounts:
    application_grpc: []
    application_rest: []
    application_scheduler: []
    application_worker: []


####################################
# pod spec (append more pod spec)
# example nodeSelect
#
# pod:
#   spec:
#     nodeSelector:
#       application: my-node-group
####################################
pod:
  spec: {}

