REMOTE_URL:
  - file:///opt/spaceone/board/config/database.yaml
  - file:///opt/spaceone/board/config/shared.yaml
  - file:///opt/spaceone/board/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  DATABASES:
    default:
      db: board
      host: mongodb
      port: 27017
      maxPoolSize: 200
      username: board_user
      password: board_password
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: redis
      port: 6379
      db: 1
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/board.log